hw10 init
alexandr-lakeev/otus-home-work pull request #11
Opened 2021-12-03 15:22 UTC by alexandr-lakeev

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-12-05 09:48 UTC, alexandr-lakeev commented
```
name             old time/op    new time/op    delta
GetDomainStat-8    3.68ms ±18%    0.00ms ±11%  -99.98%  (p=0.000 n=9+10)

name             old alloc/op   new alloc/op   delta
GetDomainStat-8    51.4kB ±35%     4.1kB ± 0%  -91.95%  (p=0.000 n=10+10)

name             old allocs/op  new allocs/op  delta
GetDomainStat-8       510 ±35%         2 ± 0%  -99.61%  (p=0.000 n=10+10)
```

2021-12-10 15:23 UTC, agneum requested changes
Спасибо за вариант решения.
Работа с сырыми байтами и нахождение позиции "Email" дают ненадежный результат
Возвращаю на доработку
Итого: 4/10

2021-12-10 15:23 UTC, agneum commented on hw10_program_optimization/stats.go
> +			}
Необходимо использовать сторонние библиотеки по ускорению анмаршалинга JSON(easyjson, jsoniter, fastjson, и т.д.), иначе решение получится ненадёжным

[Частые ошибки](https://github.com/alexandr-lakeev/otus-home-work/tree/hw10_program_optimization/hw10_program_optimization#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8):
> Работа с сырыми байтами, нахождение позиции "Email" и пр. вместо ускорения анмаршалинга более поддерживаемыми и понятными средствами.

2021-12-11 10:42 UTC, agneum approved these changes
Спасибо за правки. Отличная работа
Итого: 10/10

2021-12-11 13:31 UTC, merged